FROM        debian:buster

RUN         apt update &&\
            apt upgrade -y &&\
            apt install -y nginx openssl

WORKDIR	    /etc/nginx

RUN         mkdir -p /etc/nginx/ssl

RUN         mkdir -p /run/nginx

COPY        nginx.conf /etc/nginx/sites-available/default

COPY        nginx.conf /etc/nginx/conf.d/default.conf

CMD         ["nginx -t","systemctl restart nginx","nginx", "-g", "daemon off;"]