version: '3.9'
services:
  flask:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - flask
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
