FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf

# RUN         apt update &&\
#             apt upgrade -y &&\
#             apt install -y nginx openssl

# WORKDIR	    /etc/nginx

# RUN         mkdir -p /etc/nginx/ssl

# RUN         mkdir -p /run/nginx

# COPY        nginx.conf /etc/nginx/sites-available/default

# CMD         ["nginx", "-g", "daemon off;"]