FROM        debian:buster

RUN         apt update &&\
            apt upgrade -y

WORKDIR	    /etc/nginx

RUN         mkdir -p /run/nginx

COPY        nginx.conf /etc/nginx/conf.d/default.conf

CMD         ["nginx", "-g", "daemon off;"]