FROM        debian:buster

RUN         apt update &&\
            apt upgrade -y &&\
            apt install -y nginx openssl

WORKDIR	    /etc/nginx

RUN         mkdir -p /etc/nginx/ssl

RUN         mkdir -p /run/nginx

COPY        ./conf/nginx.conf /etc/nginx/conf.d/default.conf

ENTRYPOINT  ["/etc/nginx/configure.sh"]

CMD         ["nginx", "-g", "daemon off;"]