name: Deploy to AWS INSTACE BY Arno Baboomian

on:
  push:
    branches:
      - main  # Deploy on push to main branch
  pull_request:
    branches:
      - main  # Deploy on pull requests to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Use the version of Node.js your project needs

    - name: Install dependencies
      run: | 
        pwd ; ls

    - name: Deploy to AWS INSTACE via SSH
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        REPO: yourusername/yourrepo

      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
          pwd ;ls
          cd ~/flask
          git fetch
          git pull origin main
          make re
        EOF